### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by axetroy** [axetroy/cask.rs#26]
- [x] extrator: drop `tar` command #21 
- [x] extractor: extract file from sub-folder in tarball #29
- [x] extractor: support more tarball format
	- [x] .~7z~ it's very rare in the distribution software, so drop it
	- [x] .~rar~ it's very rare in the distribution software, so drop it
	- [x] .tar.bz2
- [ ] Stable `Cask.toml`
	 - [x] Simplify the download url #27
	 - [ ] Support checksums file
	 - [ ] Support build step instead of specify download URL
	 - [x] Support binary file in sub-folder 7ca7a8a8bb22c563166db26837a22ff73eb6ede1
	 - [ ] Implement dependencies #28
- [ ] Maybe: drop `git` command, use pure rust implement Git lib #36 
- [ ] Command-line auto-complete
- [x] ~Colorful some important information in stdout/stderr~ d882909687d039771641b8c2497cd626c5e4c010
- [x] Add check for update command #13
- [ ] A documentation website
- [x] https://github.com/axetroy/cask.rs/issues/31
- [x] Cross compile #33
